### ISSUE TITLE
AttributeError: entity

### ISSUE THREAD

**Issue by minibear0523** [pycasbin/sqlalchemy-adapter#10]
* FastAPI
* SQLAlchemy1.13 / MySQL8.0.18

code:
```python
adapter = Adapter(engine=engine)
ENFORCER = casbin.Enforcer(config.CASBIN_MODEL_CONF, adapter, True)
```

traceback:
```
INFO:     Started reloader process [1]
2020-05-04 12:38:38,201 - INFO - Model:
INFO:     Model:
2020-05-04 12:38:38,201 - INFO - r.r: sub, obj, act
INFO:     r.r: sub, obj, act
2020-05-04 12:38:38,201 - INFO - p.p: sub, obj, act
INFO:     p.p: sub, obj, act
2020-05-04 12:38:38,201 - INFO - e.e: some(where (p_eft == allow))
INFO:     e.e: some(where (p_eft == allow))
2020-05-04 12:38:38,201 - INFO - m.m: g(r_sub, p_sub) && r_obj == p_obj && r_act == p_act
INFO:     m.m: g(r_sub, p_sub) && r_obj == p_obj && r_act == p_act
2020-05-04 12:38:38,201 - INFO - g.g: _, _
INFO:     g.g: _, _
Process SpawnProcess-1:
Traceback (most recent call last):
  File "/usr/local/lib/python3.7/multiprocessing/process.py", line 297, in _bootstrap
    self.run()
  File "/usr/local/lib/python3.7/multiprocessing/process.py", line 99, in run
    self._target(*self._args, **self._kwargs)
  File "/usr/local/lib/python3.7/site-packages/uvicorn/subprocess.py", line 61, in subprocess_started
    target(sockets=sockets)
  File "/usr/local/lib/python3.7/site-packages/uvicorn/main.py", line 382, in run
    loop.run_until_complete(self.serve(sockets=sockets))
  File "uvloop/loop.pyx", line 1456, in uvloop.loop.Loop.run_until_complete
  File "/usr/local/lib/python3.7/site-packages/uvicorn/main.py", line 389, in serve
    config.load()
  File "/usr/local/lib/python3.7/site-packages/uvicorn/config.py", line 288, in load
    self.loaded_app = import_from_string(self.app)
  File "/usr/local/lib/python3.7/site-packages/uvicorn/importer.py", line 20, in import_from_string
    module = importlib.import_module(module_str)
  File "/usr/local/lib/python3.7/importlib/__init__.py", line 127, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1006, in _gcd_import
  File "<frozen importlib._bootstrap>", line 983, in _find_and_load
  File "<frozen importlib._bootstrap>", line 967, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 677, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "./main.py", line 12, in <module>
    from interfaces.router import api_router
  File "./interfaces/router.py", line 6, in <module>
    from .endpoints import identity, authentication, permission
  File "./interfaces/endpoints/identity.py", line 11, in <module>
    from application.services.security import get_current_active_user, get_current_admin_user
  File "./application/services/security.py", line 11, in <module>
    from domain.permission.entity import Policy, verify_permission
  File "./domain/permission/entity.py", line 19, in <module>
    ENFORCER = casbin.Enforcer(config.CASBIN_MODEL_CONF, adapter, True)
  File "/usr/local/lib/python3.7/site-packages/casbin/core_enforcer.py", line 31, in __init__
    self.init_with_adapter(model, adapter)
  File "/usr/local/lib/python3.7/site-packages/casbin/core_enforcer.py", line 47, in init_with_adapter
    self.init_with_model_and_adapter(m, adapter)
  File "/usr/local/lib/python3.7/site-packages/casbin/core_enforcer.py", line 63, in init_with_model_and_adapter
    self.load_policy()
  File "/usr/local/lib/python3.7/site-packages/casbin/core_enforcer.py", line 142, in load_policy
    self.adapter.load_policy(self.model)
  File "/usr/local/lib/python3.7/site-packages/casbin_sqlalchemy_adapter/adapter.py", line 50, in load_policy
    lines = self._session.query(CasbinRule).all()
  File "/usr/local/lib/python3.7/site-packages/sqlalchemy/orm/session.py", line 1558, in query
    return self._query_cls(entities, self, **kwargs)
  File "/usr/local/lib/python3.7/site-packages/sqlalchemy/orm/query.py", line 191, in __init__
    self._set_entities(entities)
  File "/usr/local/lib/python3.7/site-packages/sqlalchemy/orm/query.py", line 219, in _set_entities
    self._set_entity_selectables(self._entities)
  File "/usr/local/lib/python3.7/site-packages/sqlalchemy/orm/query.py", line 250, in _set_entity_selectables
    ent.setup_entity(*d[entity])
  File "/usr/local/lib/python3.7/site-packages/sqlalchemy/orm/query.py", line 4185, in setup_entity
    self._with_polymorphic = ext_info.with_polymorphic_mappers
  File "/usr/local/lib/python3.7/site-packages/sqlalchemy/util/langhelpers.py", line 883, in __get__
    obj.__dict__[self.__name__] = result = self.fget(obj)
  File "/usr/local/lib/python3.7/site-packages/sqlalchemy/orm/mapper.py", line 2141, in _with_polymorphic_mappers
    configure_mappers()
  File "/usr/local/lib/python3.7/site-packages/sqlalchemy/orm/mapper.py", line 3255, in configure_mappers
    mapper._post_configure_properties()
  File "/usr/local/lib/python3.7/site-packages/sqlalchemy/orm/mapper.py", line 1950, in _post_configure_properties
    prop.init()
  File "/usr/local/lib/python3.7/site-packages/sqlalchemy/orm/interfaces.py", line 196, in init
    self.do_init()
  File "/usr/local/lib/python3.7/site-packages/sqlalchemy/orm/relationships.py", line 1935, in do_init
    self._process_dependent_arguments()
  File "/usr/local/lib/python3.7/site-packages/sqlalchemy/orm/relationships.py", line 1997, in _process_dependent_arguments
    self.target = self.entity.persist_selectable
  File "/usr/local/lib/python3.7/site-packages/sqlalchemy/util/langhelpers.py", line 977, in __getattr__
    return self._fallback_getattr(key)
  File "/usr/local/lib/python3.7/site-packages/sqlalchemy/util/langhelpers.py", line 951, in _fallback_getattr
    raise AttributeError(key)
AttributeError: entity
```

**Comment by hsluoyz** [comment]
@techoner

**Comment by techoner** [comment]
@minibear0523 Make sure the database connection information is correct

**Comment by hsluoyz** [comment]
Incomplete information to answer your query.
